training:
  - _target_: torchvision.transforms.Resize
    size: ${img_resize}
  - _target_: affordance.dataloader.transforms.ColorTransform
    contrast: 0.05
    brightness: 0.05
    hue: 0.02
    prob: 1
  - _target_: affordance.dataloader.transforms.ScaleImageTensor  # Scale 0-255 to 0-1

validation:
  - _target_: torchvision.transforms.Resize
    size: ${img_resize}
  - _target_: affordance.dataloader.transforms.ScaleImageTensor  # Scale 0-255 to 0-1
