training:
  - _target_: torchvision.transforms.Resize
    size: ${aff_detection.img_size}
  - _target_: torchvision.transforms.CenterCrop
    size: ${aff_detection.img_size}
  - _target_: thesis.datasets.transforms.ScaleImageTensor  # Scale 0-255 to 0-1
  - torchvision.transforms.Normalize:
    mean: [0.18877631, 0.18877631, 0.18877631]
    std: [0.07276466, 0.07276466, 0.07276466]

validation:
  - _target_: torchvision.transforms.Resize
    size: ${aff_detection.img_size}
  - _target_: torchvision.transforms.CenterCrop
    size: ${aff_detection.img_size}
  - _target_: thesis.datasets.transforms.ScaleImageTensor  # Scale 0-255 to 0-1
  - torchvision.transforms.Normalize:
    mean: [0.18877631, 0.18877631, 0.18877631]
    std: [0.07276466, 0.07276466, 0.07276466]

