defaults:
  - robot: panda_longer_finger
  - scene: calvin_scene_D
  - env: env
  - aff_detection: cliport_pixel_lang
  - cameras: static_and_gripper_calvin
  - paths: general_paths
  - agent: base
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

data_path: ${paths.vr_data}
model_name: full

max_timesteps: 100

policy_checkpoint: 
  train_folder: ./trained_agents/D_D_static_rgb_baseline
  model_name: mcil_baseline.ckpt

aff_checkpoint:
  train_folder: ./hydra_outputs/affordance_model/2022-02-15/13-08-08_aff_rl
  model_name: val_miou.ckpt
  img_resize: 200

hough_voting:
  skip_pixels: 4
  inlier_threshold: 0.7
  angle_discretization: 100
  inlier_distance: 15
  percentage_threshold: 0.3
  object_center_kernel_radius: 10

save_dir: ./hydra_outputs/calvin
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}