defaults:
  - robot: panda_longer_finger
  - scene: calvin_scene_D
  - env: env
  - aff_detection: cliport_lang
  - cameras: static_and_gripper_calvin
  - paths: general_paths
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

data_path: ${paths.vr_data}
model_name: full

aff_checkpoint:
  path: ./hydra_outputs/affordance_model/2022-01-18/00-25-21_aff_rl
  model_name: last.ckpt
  img_resize: 224

agent:
  _target_: thesis.agents.base_agent.BaseAgent
  _recursive_: False

save_dir: ./hydra_outputs/calvin
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}