defaults:
  - robot: panda_longer_finger
  - scene: calvin_scene_A
  - env: env
  - aff_detection: cliport_lang
  - cameras: static_and_gripper
  - paths: general_paths
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

data_path: ${paths.vr_data}
model_name: full

agent:
  _target_: thesis.agent.base_agent.BaseAgent
  _recursive_: False

save_dir: ./hydra_outputs/calvin
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}