defaults:
  - robot: panda_longer_finger
  - scene: calvin_scene_D
  - env: env
  - aff_detection: cliport_lang
  - cameras: static_and_gripper_calvin
  - paths: general_paths
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

data_path: ${paths.vr_data}
model_name: full

aff_checkpoint:
  path: ./hydra_outputs/affordance_model/2022-01-27/17-06-54_aff_rl
  model_name: vapo_endpt_randShift_epoch=00_val_loss.ckpt #last.ckpt
  # path: ./hydra_outputs/affordance_model/2022-01-24/20-19-09_aff_rl
  # model_name: cliport_bs32_randShift_epoch=00_val_err.ckpt
  # path: ./hydra_outputs/affordance_model/2022-01-18/16-20-15_aff_rl
  # model_name: cliport_bs32_notrasforms_epoch=00_val_err.ckpt
  img_resize: 224

agent:
  _target_: thesis.agents.base_agent.BaseAgent
  _recursive_: False

save_dir: ./hydra_outputs/calvin
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}