defaults:
  - _self_
  - robot_io/datamodule@datamodule: default
  - robot_io/robot@robot: panda_frankx_interface
  - robot_io/env@env: env
  - robot_io/cams@cameras: camera_manager
  - agent: real_world
  - paths: general_paths
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

data_path: ${paths.vr_data}
model_name: real_world

max_timesteps: 100
agent:
  _target_: thesis.agents.real_world_agent.AffHULCAgent
  _recursive_: False
  save_viz: False
  viz_obs: True
  offset: [0.0, -0.025, 0.05]  # Relative to end effector
  model_free: 
    train_folder: ./trained_agents/lfp
    checkpoint: 30
  aff_cfg:
    train_folder: ~/logs/thesis/aff_ablation/2022-06-15/18-23-49_aff_ablation
    # train_folder: ./hydra_outputs/affordance_model/2022-03-09/01-38-55_aff_rl
    model_name: val_err.ckpt
  
seed: 42
env:
  freq: 15
panda_env_wrapper:
  max_rel_pos: 0.02
  max_rel_orn: 0.05

save_dir: ./hydra_outputs/real_world_inference
hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  searchpath:
    - pkg://robot_io.conf
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}