defaults:
  - aff_detection: cliport_lang
  - paths: general_paths
  - transforms@dataset.transforms_cfg: rgb_lang
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# folders
checkpoint:
  path: ./hydra_outputs/affordance_model/2022-01-18/00-25-21_aff_rl
  model_name: x.ckpt # cliport_bs32_epoch=00.ckpt

dataset_name: calvin_lang_contact
dataset:
  data_dir: ${paths.datasets}/${dataset_name}
  cam: static
  n_train_ep: -1  # Train using all episodes
  img_resize:
    static: 224  # clip img size
    gripper: 96
    all: 100

dataloader:
  num_workers: 4
  batch_size: 4
  pin_memory: true

#-- Hydra config --#
hydra_outputs: ./hydra_outputs/tmp/
hydra:
  run:
    dir: ${hydra_outputs}/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output