defaults:
  - aff_detection: vapo_affDir_clip
  - paths: general_paths
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

save_viz: True

# folders
load_from_last_ckpt: True
checkpoint:
  path: ./ # ${hydra_outputs}/2022-01-16/14-42-24_aff_rl
  model_name: last.ckpt # epoch=49-step=34449.ckpt
run_name: 'cliport_lang'

trainer:
  # script configs
  gpus: -1
  max_epochs: 15
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  strategy: ddp
  precision: 32

dataset_name: calvin_lang_contactSync
dataset:
  data_dir: ${paths.datasets}/${dataset_name}
  cam: static
  n_train_ep: -1  # Train using all episodes
  transforms: ${aff_detection.transforms}
  radius:
    static: 14
    gripper: 10
  img_resize:
    static: 224  # clip img size
    gripper: 96
    all: 100

dataloader:
  num_workers: 4
  batch_size: 32
  pin_memory: true

wandb:
  logger:
    name: ${run_name}_${now:%y-%m-%d}_${now:%H-%M}
    entity: affordance
    project: affordance_model
    offline: False
  saver:
    val_loss:
      monitor: 'Validation/loss'
      save_top_k: 2
      mode: min
      verbose: True
    val_err:
      monitor: 'Validation/total_attn_dist_err'
      save_top_k: 2
      mode: min
      verbose: True
      save_last: True
#-- Hydra config --#
hydra_outputs: ./hydra_outputs/affordance_model/
hydra:
  run:
    dir: ${hydra_outputs}/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output