parent_folder: ../
vr_data: ${paths.parent_folder}/calvin_env/data/

# Trained affordance models
trained_models: ${paths.vapo_path}/trained_models/

# For training affordance model
datasets: ${paths.parent_folder}/datasets/