name: cliport_pixel_lang

model:
  _target_: thesis.affordance.aff_lang_detector.AffLangDetector
  _recursive_: False
  cfg:
    batchnorm: False # important: False because batch_size=1
    lr: 1e-5
    attn_stream_fusion_type: 'add'
    lang_fusion_type: 'mult'
    load_from_last_ckpt: True
    val_repeats: 1
    streams: ${aff_detection.streams}

img_size: 224
defaults:
  - pixel_data
  - streams: clip_lingunet