model:
  _target_: thesis.affordance.aff_lang_detector.AffLangDetector
  _recursive_: False
  cfg:
    lr: 1e-5
    attn_stream_fusion_type: 'add'
    lang_fusion_type: 'mult'
    load_from_last_ckpt: True
    val_repeats: 1
    streams: ${aff_detection.streams}
    decoder_channels: [128, 64, 32]  # [256, 128, 64, 32, 16]
  hough_voting:
    skip_pixels: 2
    inlier_threshold: 0.7
    angle_discretization: 100
    inlier_distance: 10
    percentage_threshold: 0.3
    object_center_kernel_radius: 10


transforms: ${aff_detection.streams.transforms}
img_size: 224
defaults:
  - streams: rn18_bert_lingunet