# Unet Resnet 18 with respective decoder channels
# BERT as sentence encoder
# Affordance binary mask prediction
name: vapo_mask_bert

model:
  _target_: thesis.affordance.vapo_lang_detector.VAPOAffLangDetector
  _recursive_: False
  cfg:
    attn_stream_fusion_type: 'add'
    lang_fusion_type: 'mult'
    streams: ${aff_detection.streams}
    batchnorm: False
    loss:
      centers: 2.5
      dice: 5
      ce_loss: 1
      affordance:
        add_dice: true
        ce_class_weights: [0.2, 0.8]
    optimizer:
      lr: 1e-5
      weight_decay: 1e-3
    unet_cfg:
      decoder_channels: [128, 64, 32]
    hough_voting:
      skip_pixels: 2
      inlier_threshold: 0.7
      angle_discretization: 100
      inlier_distance: 10
      percentage_threshold: 0.3
      object_center_kernel_radius: 10

img_size: 224
defaults:
  - mask_data
  - streams: rn18_bert_lingunet